### ISSUE TITLE
Q: combining :currency_short and :decimal_long

### ISSUE THREAD

**Issue by DaTrader** [kipcole9/money#139] opened 2021-12-28 14:40 UTC
Kip,

I have this need to format Money in the following fashion:

$100 million
$10 thousand
$12 billion

Do you have a suggestion how I can do that?

Thanks,

Damir

**Comment by aphillipo** [comment] 2021-12-28 14:48
It's pretty easy to write such a thing... worth having a try yourself - here is an example in javascript: https://stackoverflow.com/questions/10599933/convert-long-number-into-abbreviated-string-in-javascript-with-a-special-shortn#answer-10601315 

You can just change the suffixes to be thousand, million, billion etc. and obviously rewrite the code in elixir. Let me know here if you get stuck and I'll try to help further.

**Comment by DaTrader** [comment] 2021-12-28 14:52
Of course it is easy, but I am not looking for a way to do it in general, but by leveraging the Money library which I already use heavily for formatting (having the locale/currency sensitivity in mind, of course), i.e. all that comes with a CLDR compliant lib.

**Comment by kipcole9** [comment] 2021-12-28 15:08
@DaTrader possible, but I would have to derive a composite format internally that combines the formats for decimal long with a currency code.  As you say, a composite between decimal long and currency short formats.

Placing the currency symbol would be a heuristic (in "en" the symbol for currency short formats is a prefix, in "fr" its a suffix).  Or are you looking for a standardised approach where the symbol is always a prefix?

Let me think on this a bit and revert in my morning.

**Comment by DaTrader** [comment] 2021-12-28 15:21
That's a good question. The format itself is a hybrid of something long and something short. It is still intended for table-like views but with more room. I really don't know French, but I know that in Croatia 'kn' is the shortest symbol of the local currency and it is usually stated after the amount. However, when in spreadsheets and other table views, it is not uncommon to see it prefixed as well, for you don't really want to see anything behind the 0's in a financial report as it tires the eyes.

As for my case here, I could do with either of the two options (supporting the ones where its a suffix and the ones where it's a prefix or just only the ones where it's prefixed).

In case this is a pain for you, I can do a work around and parse it back to separate the currency part and then prefix the other format (:decimal_long) with it, but that'd be lame and unsustainable in the long run for it'd be too slow on a larger scale.

**Comment by kipcole9** [comment] 2021-12-28 23:48
Thanks for the feedback.  I suspected you were after a tabular format where it would be normal to put the currency first, then the number (in some format).

As of commit [97913e4](https://github.com/elixir-cldr/cldr_numbers/commit/97913e459739d26288ac8ece50fc3e5c6686f09a), [ex_cldr_numbers](https://github.com/elixir-cldr/cldr_numbers) supports number format composition that I think is a good basis for what you are after in `ex_money`.  

### Examples

```elixir
iex> Cldr.Number.to_string!(100_000_000, format: :long) |> Cldr.Number.to_string(format: :currency) 
{:ok, "$100 million"}
iex> Cldr.Number.to_string!(100_000_000, format: :long) |> Cldr.Number.to_string(currency: :AUD)                  
{:ok, "A$100 million"}
iex> Cldr.Number.to_string!(100_000_000, format: :long) |> Cldr.Number.to_string(currency: :HRK)
{:ok, "HRK 100 million"}
iex> Cldr.Number.to_string!(100_000_000, format: :long) |> Cldr.Number.to_string(format: :currency, locale: "hr")
{:ok, "100 million kn"}
iex> Cldr.Number.to_string!(100_000_000, format: :long) |> Cldr.Number.to_string(currency: :usd, locale: "hr")         
{:ok, "100 million USD"}
iex(12)> Cldr.Number.to_string!(100_000_000, format: :short) |> Cldr.Number.to_string(format: :currency, locale: "hr")
{:ok, "100M kn"}
iex> Cldr.Number.to_string!(100_000_000, format: :short) |> Cldr.Number.to_string(format: :currency)              
{:ok, "$100M"}
```
Need to add some tests but I think the foundations are solid. I will go ahead and add the `:table_short` and `:table_long` formats to `ex_money` that leverage this composition.

Feedback and suggestions very welcome.

**Comment by DaTrader** [comment] 2021-12-29 10:00
This looks great!

**Comment by DaTrader** [comment] 2021-12-29 14:00
Here's something I can't explain (potentially a new issue):

When I validate the Money amount by relying on Ecto.Changeset.validate_number, I am not always getting the correct result (!?)
Take a look at the three consecutive dumps below:

```
amount: #Money<:EUR, 1200>
min_purchase: #Money<:EUR, 100000>
errors: [
  amount: {"less than denomination",
   [
     validation: :number,
     kind: :greater_than_or_equal_to,
     number: #Money<:EUR, 100000>
   ]},
  amount: {"less than denomination", []}
]

amount: #Money<:EUR, 1200.0>
min_purchase: #Money<:EUR, 100000>
errors: [
  amount: {"less than denomination",
   [
     validation: :number,
     kind: :greater_than_or_equal_to,
     number: #Money<:EUR, 100000>
   ]},
  amount: {"less than denomination", []}
]

amount: #Money<:EUR, 1200.00>
min_purchase: #Money<:EUR, 100000>
errors: [amount: {"less than denomination", []}]
```

Those are the results of me typing `EUR 1200` in my LiveView form and then adding a `.` then `0` and then another `0`. My own  function passed to validate_change does it correctly all three times (the one with just the error message without details), and the validate_number (with the details) does not report the error with the last '0' added as if for some reason ignoring the decimal point and treating the number as an integer (but how and why?). The errors list is reversed as the Changeset errors get prepended not appended (of course). See the code below that generates this:

```
   changeset
    |> tap( fn changeset ->
      IO.puts( "")
      get_field( changeset, :amount) |> IO.inspect( label: "amount")
      min_purchase |> IO.inspect( label: "min_purchase")
    end)
    |> validate_change( :amount, fn :amount, value ->
      if Money.cmp( value, min_purchase) >= 0 do
        []
      else
        [ { :amount, error_msg( deal, :amount_too_small)}]
      end
    end)
    |> validate_number( :amount, greater_than_or_equal_to: min_purchase, message: error_msg( deal, :amount_too_small))
    |> tap( fn changeset ->
      changeset.errors |> IO.inspect( label: "errors")
    end)
```

**Comment by kipcole9** [comment] 2021-12-29 19:49
I have published [ex_cldr_numbers version 2.24.0](https://hex.pm/packages/ex_cldr_numbers/2.24.0) with the following changelog entry:

### Enhancements

* Allowed limited forms of format composition. For example, composing a `:long` format with a `:currency` format:
```elixir
iex> Cldr.Number.to_string!(100_000_000, format: :long) |> Cldr.Number.to_string(format: :currency) 
{:ok, "$100 million"}
```

* Add format `:currency_long_with_symbol` which is a composite of `:currency_long` and the locales standard currency format. This supports formatting of of numbers like "$100 million" in the example above.

### Example in ex_money

Notice that the symbol placement is based upon the currency format for the given locale.

```elixir
iex> m = Money.new(1_000_000_000, :USD)                                                                      
#Money<:USD, 1_000_000_000>
iex> Money.to_string m, format: :currency_long_with_symbol
{:ok, "$1 billion"}
iex> Money.to_string m, format: :currency_long_with_symbol, locale: "de"
{:ok, "1 Milliarde $"}
```

**Comment by kipcole9** [comment] 2021-12-29 20:15
On your Changeset issue:  It looks to me like you are doing a term order comparison here:
>  validate_number( :amount, greater_than_or_equal_to: min_purchase, message: error_msg( deal, :amount_too_small))

Since this ultimately [calls](https://github.com/elixir-ecto/ecto/blob/64656fe72fac184d9a61fb176a1bbabb78bd9fd6/lib/ecto/changeset.ex#L316-L323) `&>=2` which is going to compare `:amount` and `:min_purchase` as structs on a term-by-term basis since both are `Money.t` structs.

Could that be the cause of the issue you are seeing (which I confess I don't fully understand from the description).

**Comment by DaTrader** [comment] 2021-12-30 08:11
> I have published [ex_cldr_numbers version 2.24.0](https://hex.pm/packages/ex_cldr_numbers/2.24.0) with the following changelog entry:

This is great.



> Since this ultimately [calls](https://github.com/elixir-ecto/ecto/blob/64656fe72fac184d9a61fb176a1bbabb78bd9fd6/lib/ecto/changeset.ex#L316-L323) `&>=2` which is going to compare `:amount` and `:min_purchase` as structs on a term-by-term basis since both are `Money.t` structs.

OMG! So I guess they don't support Decimal.t() here either. I am really glad now I've not been using Changeset validation functions for anything except for form validation. My concern here is what lies behind the design decision to compare structs in such a way. Yes, I did a mistake to presume the broader meaning of the word 'number' in the function name, but IMO, a function should at least raise if not supporting the nominal operation on a certain type, be it a primitive or a struct, for there is no way for the user to override this behavior at the struct module level.

**Comment by kipcole9** [comment] 2021-12-30 09:29
Hmmm, perhaps some changeset validation functions for `Money.t` is a reasonable idea. I'll think on it.

**Comment by DaTrader** [comment] 2021-12-30 10:24
Yes, that would be very convenient.

Now, a question regarding the errors returned by the Money.parse function. I have a problem with the parsing error messages being of variable and potentially sizeable length (the error messages are citing the input value). Also, I have a problem when the user starts typing the amount by first stating the currency so for as long as there is no number next to it, the error shows:
`Amount cannot be converted to a number: ""`.

I need to replace the former with a generic, fixed length message such as "Invalid amount", and the latter with no error message at all. As I now see it, the only way to do this is to intercept these in the LiveView generated MyApp.ErrorHelpers.error_tag/2 function, which is fine for me. But, the amount of information I get there is not enough. The details provided are the Money type tuple and the validation: :cast. as show below:

```
{"Amount cannot be converted to a number: \"\"",
 [type: {:parameterized, Money.Ecto.Composite.Type, []}, validation: :cast]}
```

Can you please also provide the error module atom itself so I can tell the errors one from another?

Thanks!

**Comment by LostKobrakai** [comment] 2021-12-30 14:41
> Hmmm, perhaps some changeset validation functions for Money.t is a reasonable idea.
I'd suggest first starting in the ecto repo and see if this can be adjusted within ecto itself, e.g. similar to how `Enum.sort` was made aware of semantic sorting over erlang term order.

**Comment by DaTrader** [comment] 2021-12-30 14:53
@LostKobrakai 

In addition, I think it'd be a good idea in general for all core API's to leverage the "Let it fail" paradigm instead of some (undocumented) behavior when it comes to unsupported types (structures).

**Comment by LostKobrakai** [comment] 2021-12-30 14:59
It may not be explicitly documented on `validate_number`, but that behaviour is explicitly documented on all elixir core api: https://hexdocs.pm/elixir/Kernel.html#module-structural-comparison. I would've expected ecto to support at lest `Decimal` comparisons already though.

**Comment by DaTrader** [comment] 2021-12-30 15:17
It may be so, but there is a discrepancy here as the function supports Decimal.t as you say (which is good), while it doesn't support another structure although its module has the function compare. So it's neither analogous to Enum.sort nor to the Erlang structural comparison.

All I am saying is that maybe a change should be considered re this comparison policy, as least in the functions that don't fail on such types. Erlang and Elixir aside, there is hardly any design related justification why a function may be able to return semantical comparison with some structures and not others while at the same time not failing those other structures.

**Comment by LostKobrakai** [comment] 2021-12-30 15:24
It seems like `validate_number` does check the key value, but doesn't check the value set for comparison to be of a proper type. It even fails when the type is `:decimal`, but not for float or integer. I've opened an issue about that: https://github.com/elixir-ecto/ecto/issues/3808

Having looked at this some more I think it doesn't make much sense for ex_money to piggyback on `validate_number` though. Money is not (just) a number, so there should be something like `validate_amount`, which does a `validate_number` on the amount field.

**Comment by DaTrader** [comment] 2021-12-30 15:28
It could stay this way for it (Money) rightfully fails if trying to compare two Money instances with different currencies.

**Comment by kipcole9** [comment] 2021-12-30 21:45
> Yes, that would be very convenient.
> 
> Now, a question regarding the errors returned by the Money.parse function. I have a problem with the parsing error messages being of variable and potentially sizeable length (the error messages are citing the input value). Also, I have a problem when the user starts typing the amount by first stating the currency so for as long as there is no number next to it, the error shows: `Amount cannot be converted to a number: ""`.
> 
> I need to replace the former with a generic, fixed length message such as "Invalid amount", and the latter with no error message at all. As I now see it, the only way to do this is to intercept these in the LiveView generated MyApp.ErrorHelpers.error_tag/2 function, which is fine for me. But, the amount of information I get there is not enough. The details provided are the Money type tuple and the validation: :cast. as show below:
> 
> ```
> {"Amount cannot be converted to a number: \"\"",
>  [type: {:parameterized, Money.Ecto.Composite.Type, []}, validation: :cast]}
> ```
> 
> Can you please also provide the error module atom itself so I can tell the errors one from another?
> 
> Thanks!

Unfortunately the `@behvaiour` for echo types specifies only two return types: `{:ok, result}` and `:error` so I don't think I can return the error class from the `money_with_currency` type.  I'll take a look at the Ecto source and see if there is any path forward on this because I too think that a single error return is a bit limiting.

I will also close this issue since it is resolved in the latest release. Of course please feel free to open new issues.

**Closed by kipcole9** 2021-12-30 21:45 UTC

**Comment by kipcole9** [comment] 2021-12-30 21:54
I was wrong, I can return a keyword list on cast error. The callback is:
```elixir
@callback cast(term) :: {:ok, term} | :error | {:error, keyword()}
```

I will create a separate issue to work on this.

**Comment by kipcole9** [comment] 2021-12-30 21:58
New issue opened: https://github.com/kipcole9/money_sql/issues/20
