### ISSUE TITLE
Working with custom currencies?

### ISSUE THREAD

**Issue by eumend** [kipcole9/money#64] opened 2018-04-03 17:23 UTC
The documentation states you can create new currencies via Cldr.Currency.new, and using that function truly creates new currencies, but how does one actually use them with "Money"? I found nothing on the docs for storing or working with custom currencies. Needless to say, I can:

`Cldr.Currency.new(:XXX)`

Alright, but when I try to use its atom (:XXX) for anything(eg, `Money.new(:XXX, 100)` ), I get:

`{:error, {Money.UnknownCurrencyError, "The currency :XXX is invalid"}}`

I thought of creating the currency and storing it in some module, but most of the Money module functions work with Money objects which need a valid atom.

For context, I'm working with cryptocurrencies and wanted to put them as custom currencies.

**Comment by kipcole9** [comment] 2018-04-03 20:53
@eumend Appreciate the report - definitely a bug.  I never completed the original design for reasons outlined below.

I will fix this in the next few hours.  I could use some feedback though.

### Current Strictness of a currency code

My original intent was to be quite strict on what is a valid currency.  The way to enforce that was intended to be:

1. A currency had to be created before use
2. The currency code had to comply with ISO4217 private currency standards (3 ASCII alphabetic characters in uppercase, starts with "X")

But now I'm thinking that that is really not a required.  As long as (2) above is followed, pre-creating the currency itself may be overkill.  And it also requires managing state which, for a single node application is easy - but for a distributed app is hard.

### Current private use codes in the ISO4217 standard

These codes all valid in `Money` today since they are valid in ISO4217.

["XBB", "XEU", "XFO", "XTS", "XBA", "XRE", "XOF", "XCD", "XDR", "XPD", "XBD",
 "XFU", "XBC", "XUA", "XAG", "XAU", "XPT", "XPF", "XXX", "XSU", "XAF"]

### Current Cryptocurrency codes

According to Wikipedia, the following is a basic list of codes commonly in use for the most well-known crypto currencies.  Several of them don't follow the ISO4217 private use code format.  Despite that, I think `Money` should continue to hold to ISO4217 and therefore `DASH`, `ETH`, `VTC` and `ZEC` would not be considered valid currency codes.

**How much of an issue is that for you?**

Code | Num | Fractional Digits | Currency | Notes
-- | -- | -- | -- | --
DASH | _ | 8 | Dash |  
ETH | _ | 18 | Ether | ETH conflicts with ISO 4217 because ET stands for Ethiopia.
VTC | _ | 8 | Vertcoin |  
XBC | _ | 8 | Bitcoin Cash | XBC conflicts with European Unit of Account 9 (E.U.A.-9)
XBT (formerly BTC) | - | 8 | Bitcoin | BTC conflicts with ISO 4217 because BT stands for Bhutan.
XLM | _ | 8 | Stellar Lumen |  
XMR | _ | 12 | Monero |  
XRP | _ | 6 | Ripple |  
ZEC

### Proposed solution

1. Validation of a currency code within Money is limited to simply being a valid ISO4217 currency code.  Either in the defined list, or 3 Alphabetic ASCII characters starting with "X"

2. No registration of a currency code is required in advance.

**Comment by eumend** [comment] 2018-04-03 21:29
I'm in favour of not requiring custom currencies to be pre-created (the library will throw anyway if I "misstype" the code in some operation after all).

At the moment and for my current use case I only need to handle a small amount of cryptocurrencies, so using, for example, "XET" for ETH should suffice.

However, I do think the ISO4217 will take its time to handle cryptos correctly, and with ERC20 Tokens thrown into the mix, that's even more 3-4 letter codes to handle. Plus, pretty much anyone can issue ERC20 tokens with their own code for use in their apps.

Most apps won't need all of them, indeed many will use either the most popular ones and/or their own issued currency, but having only two letters to define each cryptocurrency or token might cause troubles for bigger apps (eg. the project I'm working on will eventually need to support multiple cryptocurrencies).

In case supporting cryptocurrencies is on the short-term roadmap for this library, would supporting any alphabetic, 3-4 characters in length ASCII combination, plus a "This isnt a valid ISO code" warning, be ok? This is likely worth it's own Issue of course, and there might be better solutions.

**Comment by kipcole9** [comment] 2018-04-03 21:33
Thanks for the feedback.  Definitely cryptocurrencies are something I want to support - and be driven by what other developers need.

I'll go ahead and firstly get "any valid ISO4217 code" working in the next few hours.  I'd be very happy to collaborate on expanding cryptocurrency support and what that means after that, starting with your suggestion.

**Comment by kipcole9** [comment] 2018-04-04 05:38
I am close to finishing up.  The only area of incompatibility is going to be formatting output.  By default, the database schema stores money with a precision of `(20,8)` which, according to Wikipedia, isn't enough fractional precision for Ethereum and Monero.  So you would have to adjust the migration and/or the database yourself.  You ok with that?

The other part then is formatted output. Clearly there is no CLDR source of localised currency names, rounding requirements or other metadata that CLDR maintains for known currency codes.

My plan is just to default all the metadata to some hopefully "sensible defaults".  Hopefully thats ok too - because otherwise I would need to maintain a database of cryptocurrencies which would be onerous.

If there an open source database or cryptocurrency metadata?

**Comment by eumend** [comment] 2018-04-06 15:14
@kipcole9 Adjusting the migration seems simple enough, thanks!

As for a cryptocurrency metadata repository, I think this one from cryptocompare will do?

https://www.cryptocompare.com/api/#-api-data-coinlist-

It brings an array of all the coins from the website, since cryptos just keep coming I think a list this extensive is good enough for now? Also notice how some of the symbols have asterisks on them or are number (eg. "404").

**Comment by kipcole9** [comment] 2018-04-09 15:29
[Cldr version 1.5.2](https://hex.pm/packages/ex_cldr) is now published on hex.  This version supports "X" currencies.  So all `Money` functions except `to_string/2` should work with that version.  I am working on `to_string/2` now.

**Comment by kipcole9** [comment] 2018-04-09 16:28
[Cldr Numbers version 1.4.2](https://hex.pm/packages/ex_cldr_numbers) is published on hex and it supports `to_string/2` for valid but unknown currencies.

This should complete phase 1 of support for crypto currencies but I appreciated its far from what you need.  Hopefully this lets you move forward using "X" codes for now while I work on a `Money.Crypto` module and friends.

To use this, all you should have to do is update `ex_cldr` and `ex_cldr_numbers` dependencies.

```elixir
mix deps.update ex_cldr
mix deps.update ex_cldr_numbers
```

**Comment by kipcole9** [comment] 2018-04-09 16:41
I just pushed [Money version 2.5.0](https://hex.pm/packages/ex_money) to hex.  I had to fix one test to reflect the changes to ex_cldr and ex_cldr_numbers.  It also includes another unrelated feature.

I'm going to keep this issue open until I complete the `Money.Crypto` module.  Please feel free to keep the suggestions and feedback coming.

**Comment by kipcole9** [comment] 2018-04-10 12:08
I'm going to close this issue and open a new one specifically on crypto currencies.

**Closed by kipcole9** 2018-04-10 12:08 UTC
